### ISSUE TITLE
simulation result

### ISSUE THREAD

**Issue by cocolele92** [tum-esi/5GTQ#1]
I have read your article “5GTQ: QoS-Aware 5G-TSN Simulation Framework” and it has benefited me a lot. But I would like to ask you some more questions and hope to get your reply. I ran the project 5GTQ on github “[GitHub - tum-esi/5GTQ: 5GTQ: QoS-Aware 5G-TSN Simulation Framework (VTC Fall 2023 Paper)](https://github.com/tum-esi/5GTQ)”, however, the simulation result of maximum end-to-end delay in figure 7-8 in the article, how should I find this simulation result of end-to-end delay on the project 5GTQ because I am new to do this, looking forward to your reply.

**Comment by debnathr** [comment]
@cocolele92, you will find the delay results in the "results" folder after you run the simulation. In the "results" folder you will find ".vec" and ".sca"  files. You can see the delay values by opening the ".vec" file (it will ask to create a ".anf" file, click yes).

**Comment by cocolele92** [comment]
@debnathr Thank you for your reply! I still can't find the end-to-end delays of Network Control traffic, Video traffic, BE traffic,  directly from the results yet.  Based on what keywords can I find the end-to-end delays of Network Control traffic, Video traffic, BE traffic  directly from the results. Or the end-to-end delays of Network Control traffic, Video traffic, BE traffic need to be computed form the result parameters (such as "Delay at the rlc layer DL", "transmission time", "reception time").

**Comment by debnathr** [comment]
@cocolele92 the delay will be found in the receiving node application. Search for the keyword "meanBitLifeTimePerPacket". These informations are part of the INET. Check the INET documentation given below.

https://inet.omnetpp.org/docs/showcases/measurement/endtoenddelay/doc/index.html

**Comment by cocolele92** [comment]
@debnathr Thank you for your reply! After completing the simulation, my parameter "meanBitLifeTimePerPacket" had a simulation result of zero, as shown below. Is that because my simulation time is too short? Or maybe it's something else.
![微信截图_20240626203616](https://github.com/tum-esi/5GTQ/assets/147381272/2b4ca6cf-5a86-4ad2-a189-5b49a78bf101)
