### ISSUE TITLE
Can this project achieve  5G-TSN time sychronization?

### ISSUE THREAD

**Issue by w1w9** [tum-esi/5GTQ#5]
Hello sir.It is my honor to  study your project .A  question is that  can your  project achieve 5G-TSN time  sychronization ? I want to collect some data about 5G-TSN time sychronization.

**Comment by debnathr** [comment]
Hello, 
we have not considered the time sync in the entire 5G-TSN network. We made the assumption that the entire network is fully synchronized. You could send some gPTP messages and try to do the measurements though.

BR,
Rubi

**Comment by w1w9** [comment]
OK,thank  for  your  reply.Good  wishes  for you.

NBJ.

**Comment by debnathr** [comment]
future development work
