### ISSUE TITLE
Unable to import simu5g as a project

### ISSUE THREAD

**Issue by anasbinmuslim** [tum-esi/5GTQ#6]
Hello,

I am trying the 5GTQ simulation framework. After cloning the project and adding 5GTQ workspace, I tried to import existing projects which are inet, simu5g, tsnfivegcomm but only inet and tsnfivegcomm are identified as prjects to be exported.
Simu5G is not being identified as a project that can be imported.

Is there another configuration that needs to be done and isnt mentioned in Readme of 5GTQ github?

**Comment by debnathr** [comment]
All the steps are included in the Readme and there are no additional step that needs to be done. You can also import Simu5G from the Simu5G repository and import as Omnet++ project.

**Comment by anasbinmuslim** [comment]
I will try this.
Previously I thought that simu5g present in 5gtq repo was a modified version of original simu5g.
