### ISSUE TITLE
Files not found in Dstt.h

### ISSUE THREAD

**Issue by RogerJung** [tum-esi/5GTQ#7]
Hello, thanks for your open-source project about TSN-5G integration. I've tried to follow the instructions in README. However, I'm facing a problem with files not being found in the "**Simu5G**" folder when I was building the project in **opp_ide**. Is there any extra setting about the included path before I build this project?

![Screenshot from 2024-09-05 19-46-50](https://github.com/user-attachments/assets/dfab6904-efcb-4f64-857d-2a6f56ce801b)
![Screenshot from 2024-09-05 19-46-32](https://github.com/user-attachments/assets/a94a4e5f-f895-4b89-b6f7-f0dbe6f1ffb8)

**Comment by debnathr** [comment]
Hi,

Ideally it should work with the given steps. If you check the Simu5G folder, you will find the Binder.h file. 
Note: You can run the project only on Linux kernel (Ubuntu). As far as I know, Simu5G doesn't work on Windows.
